export const SET_CURRENT_PLAYER_REQUEST = 'SET_CURRENT_PLAYER_REQUEST';
export const SET_CURRENT_PLAYER = 'SET_CURRENT_PLAYER';
export const SET_PLAYER_POSITION_REQUEST = 'SET_PLAYER_POSITION_REQUEST';
export const SET_PLAYER_POSITION = 'SET_PLAYER_POSITION';
export const ROLL_DICE_REQUEST = 'ROLL_DICE_REQUEST';
export const ROLL_DICE = 'ROLL_DICE';
export const SET_WINNER_REQUEST = 'SET_WINNER_REQUEST';
export const SET_WINNER = 'SET_WINNER';

export const RESET_REQUEST = 'RESET_REQUEST';
export const RESET = 'RESET';
